### ISSUE TITLE
Strategy objects

### ISSUE THREAD

**Issue by xblahoud** [xblahoud/FiMDP#14]
Currently,

strategies returned by the Energy solvers are lists of dictionaries `(state → dict)`. The keys in the dictionaries are energy levels and values actions to pick. Intuitively, for a pair `k: α` we have that the action `α` is safe to take if the energy is at least `k`. The intended semantics is that the agent with energy `e` should pick the maximum `k` that is less or equal to `e`.

 We can implement an object, that would have the same behavior: writing `strategy[state]` would return the corresponding `dict`. On top of that, we might have some other useful functions and even set some properties of the strategies.

The most useful function would be `strategy.pick_action(state, energy)` that returns the corresponding action.

The strategy can also remember the energy level and update it by the consumption of actions returned by calls of `pick_action(state)`.

**Comment by pthangeda** [comment]
Would it make sense to include the following methods in the strategy object (I think these should be added at a later point):

1. A method that given an energy level `e` at a state returns **all** actions that can keep the agent safe. While this does not make much sense in our current scenario, we could have situations where some actions, if safe, are preferred for a secondary reason.

2. A method that returns the whole strategy object in the current form.

**Comment by xblahoud** [comment]
>     2. A method that returns the whole strategy object in the current form.

Instead, I prefer if the object only extends the current behavior of a `dict`.

**Comment by xblahoud** [comment]
> 1. A method that given an energy level e at a state returns all actions that can keep the agent safe. While this does not make much sense in our current scenario, we could have situations where some actions, if safe, are preferred for a secondary reason.

This would be some kind of permissive strategy — a strategy that shows all possible actions for the objective. We can have the support for permissive strategies later.

**Comment by xblahoud** [comment]
In the end, the code will follow the decomposition made in our [CAV paper]. Apart from **counter strategies**, we have **counter selector** and **selection rules**.

A *counter selector* is basically a mapping from states to selection rules. This is the object computed and maintained by our algorithms. A *selection rule* for a state `s` is a mapping from integer intervals to actions. This mapping is stored as a dictionary from the lower bounds of the intervals to actions to-be-taken.

Finally, a *counter strategy* needs to be initialized with a counter selector, an initial state, and an initial energy level. It maintains the energy level in its memory and picks actions based on the current state and the current energy level.

## Interface for strategies

A strategy should offer `strategy.next_action()` that picks an action based on the current energy level and current state. The function `strategy.update_state(outcome)` tells the strategy that the last action was resolved to the state `outcome`, which is the new current state. The function raises a `ValueError` if `outcome` is not a valid successor for the last action. Based on the outcome, the strategy can update its memory. The calls to `next_action()` and `update_state` should alternate. To simplify code, ```strategy.next_action(outcome)``` is a shorthand for
```python
strategy.update_state(outcome)
strategy.next_action()
```

[CAV paper]: https://link.springer.com/chapter/10.1007/978-3-030-53291-8_22

**Comment by xblahoud** [comment]
Closed by 2f0d0a5 and ecf2945.

**Comment by xblahoud** [comment]
* [ ] Tutorial notebook for strategies

**Comment by xblahoud** [comment]
See [Strategy tutorial](https://github.com/xblahoud/FiMDP/tree/next/tut/Strategies.ipynb) for more details
